### PR TITLE
fix(scripts): fix graphdef formater

### PR DESCRIPTION
**Pull request by simon-cj**
**What type of PR is this?**
/area model
/kind bug

**What this PR does / why we need it**:
fix graphdef formater

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @FogDong @judgeeeeee 

**Does this PR introduce a user-facing change?**:

```release-note
fix graphdef formater
```

### CODE REVIEW

**Comment by simon-cj** [comment]
ping @judgeeeeee

**Comment by simon-cj** [comment]
ping @FogDong

**Review by FogDong — COMMENTED** [review]
/lgtm

**Review by FogDong — COMMENTED** [review]
/lgtm

**Review by FogDong — COMMENTED** [review]
/approve

**Pull request merged**
