### PR TITLE
feat(vendor):update vendor to kubernetes v1.19.3

### PR DESCRIPTION
**Pull request by songzhiwei7**
**What type of PR is this?**

/kind feature
/area serving

**What this PR does / why we need it**:

update vendor to kubernetes v1.19.3

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @your-reviewer

**Does this PR introduce a user-facing change?**:

```release-note
update vendor to kubernetes v1.19.3
```

### CODE REVIEW

**Comment by simon-cj** [comment]
Need add description and  release-note

**Comment by songzhiwei7** [comment]
> Need add description and release-note

done

**Review by FogDong — COMMENTED** [review]
/lgtm

**Pull request merged**
