### PR TITLE
chore(*): upgrade ormb to v0.0.10

### PR DESCRIPTION
**Pull request by simon-cj**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
upgrade ormb to v0.0.10

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @FogDong @judgeeeeee 

**Does this PR introduce a user-facing change?**:

```release-note
upgrade ormb to v0.0.10
```

### CODE REVIEW

**Comment by judgeeeeee** [comment]
Do not modify the Dockerfile，you can find args ORMB_VERSION in makefile

**Comment by simon-cj** [comment]
ping @FogDong

**Comment by simon-cj** [comment]
> Do not modify the Dockerfile，you can find args ORMB_VERSION in makefile

已修改

**Review by FogDong — COMMENTED** [review]
/lgtm

**Pull request merged**
