### PR TITLE
feat: Refactor api

### PR DESCRIPTION
**Pull request by simon-cj**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @your-reviewer

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gaocegege** [comment]
I will remove the coverage diff check tomorrow.

**Comment by gaocegege** [comment]
Can you try to force push? Seems that we need a push to trigger a new Travis Build.

**Comment by simon-cj** [comment]
Force push again， all CI is passed，need give a /lgtm again

**Pull request merged**
