### PR TITLE
chore(*): update netdef dir & path

### PR DESCRIPTION
**Pull request by simon-cj**
**What type of PR is this?**
/kind bug
/area model

**What this PR does / why we need it**:
update netdef dir & path

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @judgeeeeee @FogDong 

**Does this PR introduce a user-facing change?**:

```release-note
Update netdef dir & path
```

### CODE REVIEW

**Comment by judgeeeeee** [comment]
plz add caffe -> caffemodel ，and update charts

**Comment by judgeeeeee** [comment]
LGTM

**Review by FogDong — COMMENTED** [review]
/lgtm

**Pull request merged**
