### PR TITLE
feat(action): Add publish action

### PR DESCRIPTION
**Pull request by simon-cj**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @your-reviewer

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gaocegege** [comment]
Please ping me when it is ready.

**Comment by simon-cj** [comment]
> Please ping me when it is ready.

It is not ready, just now， I merge a PR to test a simple demo, it show that `get secret` will be effective after merge only, it can not get secret in PR. So in PR can not test this action.

**Comment by gaocegege** [comment]
Gotcha

**Review by gaocegege — COMMENTED** [review]
/lgtm

**Pull request merged**
