### PR TITLE
fix(scripts): Fix install scripts to install by one key for k8s 1.14.8

### PR DESCRIPTION
**Pull request by simon-cj**
**What this PR does / why we need it**:

Fix install scripts to install by one key for k8s 1.14.8 

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @FogDong @hewenguang 

**Release note**:

```release-note
Fix install scripts to install by one key for k8s 1.14.8 
```

### CODE REVIEW

**Comment by songzhiwei7** [comment]
LGTM

**Comment by simon-cj** [comment]
ping @FogDong

**Review by FogDong — COMMENTED** [review]
/lgtm

**Pull request merged**
