### PR TITLE
fix(api): add namespace in registry api

### PR DESCRIPTION
**Pull request by FogDong**
**What this PR does / why we need it**:

fix(api): add namespace in registry api

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @simon-cj @gaocegege 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by simon-cj** [comment]
@FogDong 
CI is not pass, [the unit tests is err](https://travis-ci.org/github/kleveross/klever-model-registry/builds/711183658?utm_source=github_status&utm_medium=notification), PTAL

**Comment by gaocegege** [comment]
Can you force push to trigger another CI build?

**Pull request merged**
