### PR TITLE
feat: Update README

### PR DESCRIPTION
**Pull request by simon-cj**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @your-reviewer

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gaocegege** [comment]
Why do we still need webhook since we decide making model regsitry as a reverse proxy?

**Comment by simon-cj** [comment]
> Why do we still need webhook since we decide making model regsitry as a reverse proxy?

oh, I impl it according to discuss before, emmm, I think two options are ok, so not change plan of discuss.

**Comment by simon-cj** [comment]
hold it, I think if impl in proxy will more simple

**Comment by gaocegege** [comment]
I have no objection on it. What I care about is which way is easy to maintain.

**Pull request closed without merging**
