### PR TITLE
feat: Support gRPC and HTTP protocols

### PR DESCRIPTION
**Pull request by simon-cj**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes https://github.com/kleveross/klever-model-registry/issues/81

Reference to #

**Special notes for your reviewer**:

/cc @your-reviewer

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gaocegege** [comment]
Please fix the unit test case. https://github.com/kleveross/klever-model-registry/pull/95/checks?check_run_id=1071788614

**Comment by gaocegege** [comment]
Please link this PR to the issue https://github.com/kleveross/klever-model-registry/issues/86 in the description.

**Comment by simon-cj** [comment]
@gaocegege PTAL

**Review by gaocegege — COMMENTED** [review]
/lgtm

**Pull request merged**
